apiVersion: v1
kind: Pod

metadata:
  name: final-exam-pod
  labels:
    app: final-exam

spec:
  containers:

  - name: mysql
    image: mysql:8

    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "Hello@123"

      - name: MYSQL_DATABASE
        value: "B-CHANTHA_Mengkong-db"

    ports:
      - containerPort: 3306

  - name: web
    image: id-card-system:latest
    imagePullPolicy: Never

    ports:
      - containerPort: 8080
      - containerPort: 22

  - name: phpmyadmin
    image: phpmyadmin/phpmyadmin

    env:
      - name: PMA_HOST
        value: "127.0.0.1"

      - name: PMA_PORT
        value: "3306"

    ports:
      - containerPort: 80